first commit after resolving comments
liveasy97/transporterApi pull request #3
Opened 2021-04-17 11:03 UTC by vivekbhosale

2021-04-17 11:40 UTC, jsrub commented on TransporterAPI/HELP.md
> +# Getting Started
Add such files to gitignore check https://github.com/spring-projects/spring-boot/blob/master/.gitignore

2021-04-17 11:58 UTC, jsrub requested changes
Reply to the comments when the changes are done.

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/mvnw
> +#!/bin/sh
https://github.com/spring-projects/spring-boot/blob/master/.gitignore

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/mvnw.cmd
> +@REM ----------------------------------------------------------------------------
https://github.com/spring-projects/spring-boot/blob/master/.gitignore

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Controller/Controller.java
> +	public List<Transporter> getApproved(@RequestParam boolean approved){
lets standardise response models. TransporterCreateResponse,TransporterUpdateResponse etc.

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Entity/Transporter.java
> +	private UUID transporter_id;
change variable name to id.

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Entity/Transporter.java
> +	private long phone_no;
follow camelCase in place of snake_case

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		responseTransporter.setMessage("Please wait for liveasy will approved your request");
Add these constants and messages to a CommonConstants class

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +	public ResponseTransporter addTransporter(Transporter transporter) {
Add validations for all the methods

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		if(approved==true) {
i think "if(approved)" will be enough since approved is a boolean

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		else if(approved==false) {
if(!approved) here

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +			for(Transporter t: transporterdao.findAll()) {
Don't call the dao like this. you can make custom queries to query only for approved ==false or approved == true entries. This makes too many unnecessary calls to the DB

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +			return responseUpdate;
set Status as well.

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +			return ResponseEntity.status(HttpStatus.OK).body("Account does not exist");
can you reply to this comment with the output this function gives when we run it on Postman. need to decide if we want to use custom response models or ResponseEntity

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/target/classes/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
add build files,bin,zip etc in .gitignore

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Entity/Transporter.java
> +	@GeneratedValue(strategy = GenerationType.AUTO)
this will not work for UUID. need to call UUID.randomUUID() in the service method.

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +	public ResponseUpdate updateTransporter(UUID transporter_id) {
is this function doing the intended task? I think this will have TransporterUpdateRequest as an input as well.

2021-04-17 11:58 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Controller/Controller.java
> +	public ResponseUpdate updateTransporter(@PathVariable UUID transporter_id){
is this function doing the intended task? I think this will have TransporterUpdateRequest as an input as well.

2021-04-18 03:45 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +			return ResponseEntity.status(HttpStatus.OK).body("Account does not exist");
It is showing internal server error. Custom response models will work fine. Will replace RessponseEntity with response models.

2021-04-18 04:57 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Entity/Transporter.java
> +	@GeneratedValue(strategy = GenerationType.AUTO)
But, I am able to generate UUID in post method.

2021-04-18 05:01 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +	public ResponseUpdate updateTransporter(UUID transporter_id) {
Account is getting updated showing message and status. But it is not working with incorrect id. I am working on it to through exception on entering incorrect id.

2021-04-18 10:45 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +	public ResponseUpdate updateTransporter(UUID transporter_id) {
Ok. I basically meant that when we update transporter we might want to update other details of the transporter as well. aside from approval.

2021-04-18 10:47 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Entity/Transporter.java
> +	@GeneratedValue(strategy = GenerationType.AUTO)
That's fine then. But i think we'll need to change the id anyway since we are thinking of composing ids as string like -> "transporter:<UUID>" for transporter etc.

2021-04-18 17:47 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Entity/Transporter.java
> +	@GeneratedValue(strategy = GenerationType.AUTO)
Yes, I think we will have to change it to string where we can keep transporter part as constant and remaining id part as variable.

2021-04-18 17:53 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +	public ResponseUpdate updateTransporter(UUID transporter_id) {
For now, update is just working to set approval value from false to true. If there is some additional changes, then we can update it later.

2021-05-27 14:02 UTC, closed without merging