Able to update name, kyc, approved status.
liveasy97/transporterApi pull request #5
Opened 2021-04-20 13:00 UTC by vivekbhosale

2021-04-20 15:12 UTC, jsrub commented
Lets keep this PR only for further comments and resolution.

2021-04-20 15:42 UTC, jsrub requested changes
Lets keep this same PR for future comments and resolution. Reply to the comments when done.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/.mvn/wrapper/MavenWrapperDownloader.java
> +/*
what is the use of this file

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/pom.xml
> +	<description>Demo project for Spring Boot</description>
change description

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Controller/TransporterController.java
> +	public List<Transporter> getApproved(@RequestParam boolean approved){
make the request param as optional.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Controller/TransporterController.java
> +	public List<Transporter> allTransporter(){
merge this function and the function below it

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Entity/Transporter.java
> +	private UUID id;
change id to string -> "transporter:UUID" .you can do this by calling UUID.randomUUID() in service method

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Entity/Transporter.java
> +	private long phoneNo;
I think this should be a string since phoneNo can be represented like +91XYZ or 902-233-32341. It's better to keep it as string so this can be made generic

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +	public TransporterResponse addTransporter(Transporter transporter) {
Use different model for Request than Transporter. call it TransporterCreateRequest where the id field will not be there.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +			transporterResponse.setMessage("Enter name");
add constants like "Error" or "Enter name" to a CommonConstants.java file. this file should be in constants package.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +			transporterResponse.setMessage("Enter name");
Declare them static and use those constants here.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +			transporterResponse.setMessage("Enter contact number");
Declaring and using exceptions can be considered here and all the other places where there is an error.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		if(transporter.getPhoneNo()==0) {
is this validation correct?

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		if(transporter.getPhoneNo()==0) {
Add Regular expression for validating phone numbers.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		List<Transporter> allTransporters = transporterdao.findAll();
you are wasting a lot of computation here.  Imagine if there are large number of transporters and you are getting all of them first and then checking for equal phone numbers. Instead you can make a custom query in the dao to search for transporter with the given phone number. It would look something like this. 
Transporter transporter = transporterdao.findByPhoneNumber(phoneNo);
if(transporter !=null)
{
     //throw exception.
}
You have to understand a majority of bottlenecks in system are due to databases.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		//transporter.setKyc("s3 link");
these should not be set by default. this statement would be something like transporter.setApproved(transporter.getApproved). which is also why i asked you to create a separate request model for the requests.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		List<Transporter> allTransporters = transporterdao.findAll();
same comment as above. you are wasting lot of db calls here. queries can do this in a optimised way.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +	public TransporterResponse updateTransporter(UUID id, Transporter transporter2) {
again the request model should be separate class called TransporterUpdateRequest

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		if(transporter2.getPhoneNo()!=0) {
use regex to validate phone numbers.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		transporter.setApproved(transporter2.isApproved());
add check here as well. If we want to change approved status we'll send it explicitly otherwise it should be null

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		if(transporter.getId()==null) {
if the transporter is null you will get a null pointer exception here.

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +			transporter=transporterdao.findById(id).get();
if no transporter exists you will get a null pointer exception here

2021-04-20 15:42 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +			transporter=transporterdao.findById(id).get();
Remove the exception part. handle it this way 
Optional<Transporter> transporter = transporterdao.findById(id);
if(transporter.isPresent())
{
     t = transporter.get();
}

2021-04-22 03:55 UTC, vivekbhosale commented on TransporterAPI/pom.xml
> +	<description>Demo project for Spring Boot</description>
Done

2021-04-22 05:04 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		if(transporter.getPhoneNo()==0) {
It is used only to check whether phone number is passed as a key in request body or not. Problem that can occur is, if user enter 0 as a value, it will not through an error. It will not affect database at all as we are not calling setter method of phone number. I will try to use regular expression or we can create another class which has only 3 member variables name, kyc and approved. If user enters phone number then we can throw exception similar to argument not found.

2021-04-22 07:38 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		List<Transporter> allTransporters = transporterdao.findAll();
Done

2021-04-22 07:39 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		List<Transporter> allTransporters = transporterdao.findAll();
Instead of transporter I have used String as return type. If string is not null, it will throw an error.

2021-04-22 07:44 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		//transporter.setKyc("s3 link");
Done

2021-04-22 08:04 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		List<Transporter> allTransporters = transporterdao.findAll();
Done

2021-04-22 08:05 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +	public TransporterResponse updateTransporter(UUID id, Transporter transporter2) {
Okay. I will separate response models all create, update and delete

2021-04-22 08:06 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +	public TransporterResponse updateTransporter(UUID id, Transporter transporter2) {
I will create separate response models for create, update and delete

2021-04-22 08:18 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		transporter.setApproved(transporter2.isApproved());
Data type of approved is boolean and default value of boolean is false. If we send it explicitly it will set approved status which is passed in request body otherwise it will set approved status as default value which is false.

2021-04-22 08:22 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +			transporter=transporterdao.findById(id).get();
Okay

2021-04-23 08:01 UTC, closed without merging