Added all test cases, resolved all errors and added company name column
liveasy97/transporterApi pull request #8
Opened 2021-04-28 07:34 UTC by vivekbhosale

Added all test cases, resolved all errors and added company name column

2021-04-28 14:49 UTC, jsrub commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Constants/CommonConstants.java
> +@Data
i don't think @data is needed here. make all the variables static and use them directly. like CommonConstants.error

2021-04-28 15:03 UTC, jsrub requested changes
keep up the good work. Just one major issue that i found that while writing tests we need to use mockito framework. We write tests cases for controller and service layers separately. read a bit more about this.We can leave this for now.But you should read about it. It will be good for your learning.

2021-04-29 06:26 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Constants/CommonConstants.java
> +@Data
Done

2021-04-29 06:29 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Model/TransporterCreateRequest.java
> +package com.springboot.TransporterAPI.Model;
Should it be for e.g TransporterCreateResponse instead of TransporterCrreateRequest?

2021-04-29 06:32 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		//System.out.println("Data is: " +a);
Done

2021-04-29 06:35 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		//System.out.println(b);
Done

2021-04-29 07:21 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Dao/TransporterDao.java
> +	String findByPhoneNo(long phoneNo);
Removed some queries which are natively supported by JPA. Only findByPhoneNo and findByApproved are not supported.

2021-04-29 09:24 UTC, vivekbhosale commented on TransporterAPI/src/main/java/com/springboot/TransporterAPI/Services/TransporterServiceImpl.java
> +		}
Above condition is used only to check if phone number is present in JSON object or not. If it is not present, then it takes default value as 0. Second condition is for validation, so there we can use regex. First condition will throw error to enter phone number if not present and second condition will throw error for improper format.

2021-04-29 10:24 UTC, closed without merging